# ~/.tmuxinator/monitor.yml

name: thorough
root: ~/thoroughcare/thoroughcare

windows:
  - status_things:
      layout: main-vertical
      panes:
        - v .
        - echo "hello"
  - testing:
      layout: tiled
      panes:
        - echo "testing"
  - running_app:
      layout: main-vertical
      panes:
        - ls
  - console_app:
      layout: main-vertical
      panes:
        - ls
