#!/usr/bin/env bash
# Install native apps
#
# Usage: `brew bundle Caskfile`

brew install caskroom/cask/brew-cask;
brew tap caskroom/versions;

brew cask install dropbox 2> /dev/null;
brew cask install google-chrome 2> /dev/null;
brew cask install iterm2 2> /dev/null;
brew cask install macvim 2> /dev/null;
brew cask install sublime-text 2> /dev/null;
brew cask install the-unarchiver 2> /dev/null;
brew cask install alfred; 
brew cask install dash;
brew cask install spectacle;
brew cask install onepassword;
brew cask install mactex;
brew cask install atom; 
brew cask install docker;

brew tap homebrew/cask-fonts;
brew cask install font-hack-nerd-font;
brew install --cask miniconda
