#!/usr/bin/env bash
# Install native apps
#
# Usage: `brew bundle Caskfile`

brew install caskroom/cask/brew-cask;
brew tap caskroom/versions;

brew  install dropbox 2> /dev/null;
brew  install google-chrome 2> /dev/null;
brew  install iterm2 2> /dev/null;
brew  install macvim 2> /dev/null;
brew  install sublime-text 2> /dev/null;
brew  install the-unarchiver 2> /dev/null;
brew  install alfred; 
brew  install dash;
brew  install spectacle;
brew  install onepassword;
brew  install mactex;
brew  install atom; 
brew  install docker;
brew install notion
brew install --cask microsoft-outlook
brew install tableplus
brew install slack

brew tap homebrew/cask-fonts;
brew  install font-hack-nerd-font;
brew install  miniconda

