require "rake"

desc "install dot files"
task :install do
	install_oh_my_zsh
	switch_to_zsh
  install_vundle
  start_up
  system %Q{rcup}
end


def switch_to_zsh
  if ENV["SHELL"] =~ /zsh/
    puts "using zsh"
  else
    print "switch to zsh? (recommended) [ynq] "
    case $stdin.gets.chomp
    when 'y'
      puts "switching to zsh"
      system %Q{chsh -s `which zsh`}
    when 'q'
      exit
    else
      puts "skipping zsh"
    end
  end
end


def install_oh_my_zsh
    print "install oh-my-zsh? [ynq] "
    case $stdin.gets.chomp
    when 'y'
      puts "installing oh-my-zsh"
      system %Q{git clone https://github.com/robbyrussell/oh-my-zsh.git "$HOME/.oh-my-zsh"}
    when 'q'
      exit
    else
      puts "skipping oh-my-zsh, you will need to change ~/.zshrc"
    end
end

def install_vundle  
  if File.exist?(File.join(ENV['HOME'], ".vim/bundle/Vundle.vim"))
      system %Q{git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim}
      system %Q{vim -u $HOME/.vimrc.bundles +BundleInstall +qa}
  end
end

def start_up
  system %Q{\curl -sSL https://get.rvm.io | bash -s stable --ruby} # rvm
  system %Q{ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"} # hombrew
  system %Q{brew tap thoughtbot/formulae}
  system %Q{brew install rcm}
  system %Q{env RCRC=$HOME/dotfiles/rcrc rcup}
  system %Q{sh brew_Install}
  system %Q{sh cask_Install}
end
